version: '3.8'

services:
  app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
